version: '3.8'

volumes: 
 data: {}

services:
  app:
    container_name: app
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
    volumes:
    - .:/src/app

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: always
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"