apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-monolith
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-monolith
  template:
    metadata:
      labels:
        app: tech-challenge-monolith
    spec:
      containers:
      - name: tech-challenge-monolith
        image: aureobueno/tech-challenge-monolith
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
