apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-monolith
  labels:
    app: tech-challenge-monolith
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-monolith
  template:
    metadata:
      labels:
        app: tech-challenge-monolith
    spec:
      containers:
        - name: tech-challenge-monolith
          image: aureobueno/tech-challenge-monolith:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: CONFIG_FILE
              value: "/app/config/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              subPath: config.yaml
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: tech-challenge-config
