apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-monolith
spec:
  selector:
    app: tech-challenge-monolith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
