name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t luizpainodev/tech-challenge-monolith:latest .
          docker push luizpainodev/tech-challenge-monolith:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig
        run: aws eks --region us-east-1 update-kubeconfig --name tech-chalenge-monolith

      - name: Create ConfigMap from .env file
        run: kubectl create configmap tech-challenge-config --from-env-file=.env

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f service.yaml
          kubectl apply -f deployment.yaml

      - name: Deploy to EKS
        run: |
          kubectl set image deployment/tech-challenge-monolith tech-challenge-monolith=luizpainodev/tech-challenge-monolith:latest
